import { ArrowLeft, BookMarked, Database, LockKeyhole, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { Brand } from "../components/Brand";

export const metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return <main className="legal-page"><header><Link href="/"><Brand /></Link><Link href="/"><ArrowLeft size={15} /> Back home</Link></header><article><span className="eyebrow">PLAIN-LANGUAGE PRIVACY</span><h1>Privacy at Tabloom</h1><p className="legal-lead">Your saved links are yours. Tabloom uses the minimum browser access needed to organize tabs and does not sell personal data or use it for advertising.</p><section><ShieldCheck /><div><h2>What we store</h2><p>Your Google account identifier, spaces, collections, saved-link titles, URLs, notes, favicon addresses, and ordering. Authentication and database records are handled by Supabase.</p></div></section><section><LockKeyhole /><div><h2>Chrome permissions</h2><p>The extension uses tabs access for the current-tabs sheet, storage for cached workspace data and sign-in state, and identity for Google OAuth. Bookmark access is optional and requested only after you start a bookmark sync. Unsupported internal browser pages are never saved.</p></div></section><section><BookMarked /><div><h2>Manual bookmark sync</h2><p>Only when you choose to sync, Tabloom uploads bookmark titles, URLs, folder paths, ordering, your device name and sync status, and sync timestamps. Forgetting a device removes its uploaded snapshot and never changes your Chrome bookmarks.</p></div></section><section><Database /><div><h2>Sharing and control</h2><p>Collection sharing is off by default. Anyone with an enabled share URL can view that collection without signing in, and future synced edits appear when they reload. Shared snapshots contain the collection name and its saved cards, but not your account identity, space name, device details, or sync state. Regenerating or disabling a link revokes the previous URL immediately. You can also edit or delete saved links and collections at any time.</p></div></section><p className="legal-note">This project ships as a self-hostable v1. Before public commercial operation, the operator should add contact details, jurisdiction-specific disclosures, and a formal account-deletion request channel.</p></article></main>;
}
