import { afterEach, describe, expect, it, vi } from "vitest";

import {
  SupabaseUpstreamAuth,
  UpstreamSupabaseAuthError,
  type SupabaseAuthClientFactory,
  type SupabaseAuthStorage,
} from "../../services/tabloom-mcp/src/oauth/upstream-supabase";

const SUPABASE_URL = "https://example.supabase.co";
const CALLBACK = "https://tabloom-mcp.vercel.app/oauth/callback/supabase";
const USER_ID = "4f6f8607-9439-4ce3-a19e-f5a302ef3e68";
const VERIFIER = "v".repeat(64);
const NOW = 1_788_000_000;

type AuthOverrides = {
  oauth?: { data: { url: string | null }; error: unknown };
  exchange?: { data: Record<string, unknown>; error: unknown };
  user?: { data: Record<string, unknown>; error: unknown };
};

function successfulSession(overrides: Record<string, unknown> = {}) {
  return {
    session: {
      access_token: "supabase-access-token",
      refresh_token: "supabase-refresh-token",
      expires_at: NOW + 3600,
      user: { id: USER_ID },
      ...overrides,
    },
    user: { id: USER_ID },
  };
}

function fakeFactory(overrides: AuthOverrides = {}) {
  const calls: Array<{ url: string; anonKey: string; options: Parameters<SupabaseAuthClientFactory>[2] }> = [];
  const storageSnapshots: Array<Record<string, string | null>> = [];
  const oauthInputs: unknown[] = [];
  const exchangeCodes: string[] = [];
  const getUserTokens: string[] = [];
  const factory: SupabaseAuthClientFactory = (url, anonKey, options) => {
    calls.push({ url, anonKey, options });
    const storage = options.auth.storage;
    const storageKey = options.auth.storageKey;
    return {
      auth: {
        async signInWithOAuth(input) {
          oauthInputs.push(input);
          await storage.setItem(`${storageKey}-code-verifier`, JSON.stringify(VERIFIER));
          const result = overrides.oauth ?? {
            data: { url: "https://example.supabase.co/auth/v1/authorize?provider=google" },
            error: null,
          };
          return result;
        },
        async exchangeCodeForSession(code) {
          exchangeCodes.push(code);
          storageSnapshots.push({
            verifier: JSON.parse((await storage.getItem(`${storageKey}-code-verifier`)) ?? "null") as string | null,
            session: await storage.getItem(storageKey),
          });
          return overrides.exchange ?? { data: successfulSession(), error: null };
        },
        async getUser(accessToken) {
          getUserTokens.push(accessToken);
          return overrides.user ?? { data: { user: { id: USER_ID } }, error: null };
        },
      },
    };
  };
  return { factory, calls, storageSnapshots, oauthInputs, exchangeCodes, getUserTokens };
}

afterEach(() => {
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("server-side Supabase upstream authentication", () => {
  it("captures the verifier generated by the real Supabase PKCE client without a browser redirect", async () => {
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key");

    const login = await auth.begin(CALLBACK);

    const provider = new URL(login.providerUrl);
    expect(provider.origin + provider.pathname).toBe(`${SUPABASE_URL}/auth/v1/authorize`);
    expect(provider.searchParams.get("provider")).toBe("google");
    expect(provider.searchParams.get("redirect_to")).toBe(CALLBACK);
    expect(provider.searchParams.get("code_challenge_method")).toBe("s256");
    expect(provider.searchParams.get("code_challenge")).toMatch(/^[A-Za-z0-9_-]{43}$/);
    expect(login.codeVerifier).toMatch(/^[A-Za-z0-9._~-]{43,128}$/);
  });

  it("preloads the verifier for the real Supabase exchange and validates its access token", async () => {
    const expiresAt = Math.floor(Date.now() / 1000) + 3600;
    const requests: Array<{ url: string; init?: RequestInit }> = [];
    vi.stubGlobal("fetch", vi.fn(async (input: string | URL | Request, init?: RequestInit) => {
      const url = String(input);
      requests.push({ url, init });
      if (url.endsWith("/auth/v1/token?grant_type=pkce")) {
        return Response.json({
          access_token: "supabase-access-token",
          refresh_token: "supabase-refresh-token",
          token_type: "bearer",
          expires_in: 3600,
          expires_at: expiresAt,
          user: { id: USER_ID },
        });
      }
      if (url.endsWith("/auth/v1/user")) return Response.json({ id: USER_ID });
      throw new Error("unexpected Supabase request");
    }));
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key");

    await expect(auth.exchange("supabase-code", VERIFIER)).resolves.toEqual({
      userId: USER_ID,
      accessToken: "supabase-access-token",
      refreshToken: "supabase-refresh-token",
      accessTokenExpiresAt: expiresAt,
    });

    expect(requests).toHaveLength(2);
    expect(JSON.parse(String(requests[0]!.init?.body))).toMatchObject({
      auth_code: "supabase-code",
      code_verifier: VERIFIER,
    });
    expect(new Headers(requests[1]!.init?.headers).get("Authorization"))
      .toBe("Bearer supabase-access-token");
  });

  it("starts Google PKCE with isolated in-memory storage and discards the verifier", async () => {
    const fake = fakeFactory();
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key", fake.factory, () => NOW);

    await expect(auth.begin(CALLBACK)).resolves.toEqual({
      providerUrl: "https://example.supabase.co/auth/v1/authorize?provider=google",
      codeVerifier: VERIFIER,
    });

    expect(fake.calls).toHaveLength(1);
    expect(fake.calls[0]!.url).toBe(SUPABASE_URL);
    expect(fake.calls[0]!.options.auth).toMatchObject({
      flowType: "pkce",
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    });
    expect(fake.oauthInputs).toEqual([{
      provider: "google",
      options: { redirectTo: CALLBACK, skipBrowserRedirect: true },
    }]);
    const storage: SupabaseAuthStorage = fake.calls[0]!.options.auth.storage;
    await expect(storage.getItem(`${fake.calls[0]!.options.auth.storageKey}-code-verifier`))
      .resolves.toBeNull();
  });

  it("exchanges with only the cookie-bound verifier and validates the access token user", async () => {
    const fake = fakeFactory();
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key", fake.factory, () => NOW);

    await expect(auth.exchange("supabase-code", VERIFIER)).resolves.toEqual({
      userId: USER_ID,
      accessToken: "supabase-access-token",
      refreshToken: "supabase-refresh-token",
      accessTokenExpiresAt: NOW + 3600,
    });
    expect(fake.storageSnapshots).toEqual([{ verifier: VERIFIER, session: null }]);
    expect(fake.exchangeCodes).toEqual(["supabase-code"]);
    expect(fake.getUserTokens).toEqual(["supabase-access-token"]);
    const storage = fake.calls[0]!.options.auth.storage;
    await expect(storage.getItem(`${fake.calls[0]!.options.auth.storageKey}-code-verifier`))
      .resolves.toBeNull();
  });

  it.each([
    ["provider start error", { oauth: { data: { url: null }, error: new Error("provider secret") } }],
    ["missing provider URL", { oauth: { data: { url: null }, error: null } }],
  ])("fails closed on %s without exposing provider details", async (_label, overrides) => {
    const fake = fakeFactory(overrides);
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key", fake.factory, () => NOW);

    const operation = auth.begin(CALLBACK);
    await expect(operation).rejects.toBeInstanceOf(UpstreamSupabaseAuthError);
    await expect(operation).rejects.not.toThrow("provider secret");
  });

  it("fails closed when Supabase does not persist a PKCE verifier", async () => {
    const factory: SupabaseAuthClientFactory = () => ({
      auth: {
        async signInWithOAuth() { return { data: { url: "https://example.supabase.co/auth" }, error: null }; },
        async exchangeCodeForSession() { throw new Error("unused"); },
        async getUser() { throw new Error("unused"); },
      },
    });
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key", factory, () => NOW);
    await expect(auth.begin(CALLBACK)).rejects.toBeInstanceOf(UpstreamSupabaseAuthError);
  });

  it.each([
    ["exchange error", { exchange: { data: {}, error: new Error("exchange detail") } }],
    ["missing access token", { exchange: { data: successfulSession({ access_token: "" }), error: null } }],
    ["missing refresh token", { exchange: { data: successfulSession({ refresh_token: "" }), error: null } }],
    ["missing expiry", { exchange: { data: successfulSession({ expires_at: undefined }), error: null } }],
    ["expired inner token", { exchange: { data: successfulSession({ expires_at: NOW }), error: null } }],
    ["invalid outer UUID", { exchange: { data: { ...successfulSession(), user: { id: "not-a-uuid" } }, error: null } }],
    ["invalid session UUID", { exchange: { data: successfulSession({ user: { id: "not-a-uuid" } }), error: null } }],
    ["invalid validated UUID", { user: { data: { user: { id: "not-a-uuid" } }, error: null } }],
    ["mismatched validated user", { user: { data: { user: { id: "95bda9f2-a8a7-4b68-ae38-98b0e9c1553b" } }, error: null } }],
    ["user validation error", { user: { data: { user: null }, error: new Error("validation detail") } }],
  ])("rejects an invalid Supabase session: %s", async (_label, overrides) => {
    const fake = fakeFactory(overrides as AuthOverrides);
    const auth = new SupabaseUpstreamAuth(SUPABASE_URL, "anon-key", fake.factory, () => NOW);
    await expect(auth.exchange("supabase-code", VERIFIER))
      .rejects.toBeInstanceOf(UpstreamSupabaseAuthError);
  });
});
